window.THEMES.sb02b = [
	"biscuits",
	"some tomatoes",
	"sweater",
	"sunglasses",
	"mobile phone",
	"stereo",
	"trainers",
	"jeans",
	"thirty-three",
	"forty-four",
	"fifty-five",
	"sixty-six",
	"seventy-seven",
	"eighty-eight",
	"ninety-nine",
	"one hundred",
	"Do you like pasta?",
	"Anything else?",
	"No, thanks",
	"Here you are",
	"Thank you",
	"You're welcome",
	"How much is it?",
	"It's cheap",
	"It's expensive"
];