window.THEMES.sb03b = [
	"tall",
	"Brazil",
	"Canada",
	"Italy",
	"Japan",
	"Mexico",
	"The United Kingdom",
	"The United States",
	"computer",
	"headphones",
	"handbag",
	"trousers",
	"roller skates",
	"towel",
	"Mike's jacket",
	"Calvin's glasses",
	"What have you got?",
	"I've got stickers",
	"I love animals",
	"I like cats",
	"I don't like monsters",
	"Where are you from?",
	"I'm from Brazil",
	"She's a teacher",
	"He's my friend"
];